# Pangomicro / Hercules-2 — chip registry
# Newest Pango high-end. PDS.

Producer: Pangomicro
Family: Hercules-2
Description: Newest Pango high-end. PDS.
DefaultToolchains:
  - pango_ds[*]
Chips:
  - Id: PGH2L75H-6FBG676
