# Pangomicro / Titan-2 — chip registry
# 28 nm Titan II. PDS.

Producer: Pangomicro
Family: Titan-2
Description: 28 nm Titan II. PDS.
DefaultToolchains:
  - pango_ds[*]
Chips:
  - Id: PG2T560HFBG676
  - Id: PGT2L100H-6FBG676
  - Id: PG2T390H-6IFFBG900
