# Efinix / Titanium
# 16 nm Titanium (some SKUs with hard RISC-V). Efinity.

Producer: Efinix
Family: Titanium
Description: 16 nm Titanium (some SKUs with hard RISC-V). Efinity.
Boards:
  - Id: efinix_ti120_devkit
    BoardName: Titanium Ti120 Development Kit
    BoardProducer: efinix
    Chip: Ti120F324C4
    Bridges:
      - jtag
    Programmer: efinity_pgm
    Status: eol
  - Id: efinix_ti180_devkit
    BoardName: Titanium Ti180 Development Kit
    Devices:
      - microsd_socket_generic
    BoardProducer: efinix
    Chip: Ti180M484C4
    Bridges:
      - jtag
    Programmer: efinity_pgm
    BoardURL: "https://www.efinixinc.com/products-devkits-titaniumti180j484.html"
  - Id: efinix_ti35_devkit
    BoardName: Titanium Ti35 Development Kit
    BoardProducer: efinix
    Chip: Ti35F256C4
    Bridges:
      - jtag
    Programmer: efinity_pgm
    Status: eol
  - Id: efinix_ti375_devkit
    BoardName: Titanium Ti375 Development Kit
    Devices:
      - microsd_socket_generic
      - emmc_chip_generic
    BoardProducer: efinix
    Chip: Ti375C529C4
    Bridges:
      - jtag
    Programmer: efinity_pgm
    BoardURL: "https://www.efinixinc.com/products-devkits-titaniumti375c529.html"
  - Id: efinix_ti375_n1156_devkit
    BoardName: Titanium Ti375 N1156 Development Kit
    Devices:
      - microsd_socket_generic
      - emmc_chip_generic
    BoardProducer: efinix
    Chip: Ti375N1156C4
    Bridges:
      - usb-jtag
    Programmer: efinity_pgm
    ExtraProgrammers:
      - openFPGALoader[*]
    Features:
      - lpddr4_memory
      - qspi_flash
      - emmc_flash
      - microsd_socket
      - ethernet_phy_gigabit
      - fmc_hpc
      - mipi_csi2_input
      - mipi_dsi_output
      - user_leds
      - user_buttons
      - usb_uart_bridge
      - usb_jtag_bridge
    BoardURL: https://www.efinixinc.com/products-devkits-titaniumti375n1156.html
    Status: active
  - Id: efinix_ti60_devkit
    BoardName: Titanium Ti60 F225 Development Kit
    Devices:
      - microsd_socket_generic
    BoardProducer: efinix
    Chip: Ti60F225C4
    Bridges:
      - jtag
    Programmer: efinity_pgm
    BoardURL: https://www.efinixinc.com/products-devkits-titaniumti60f225.html
