# efinix / topaz

Producer: efinix
Family: topaz
Description: ""
Boards:
  - Id: efinix_topaz_tz170_j484_devkit
    BoardName: "Topaz Tz170 J484 Development Kit"
    BoardProducer: efinix
    Chip: Tz170J484C4
    Bridges:
      - jtag
      - usb_uart
    Programmer: efinity_pgm
    Features:
      - jtag_header
      - usb_uart_bridge
      - mipi_dsi_output
      - mipi_csi2_input
      - lpddr4_memory
      - microsd_socket
      - user_leds
      - user_buttons
      - spi_flash
      - fmc_lpc
    Devices:
      - microsd_socket_generic
    BoardURL: "https://www.efinixinc.com/products-devkits-topaztz170j484.html"
    Status: active
