# alinx_ax7z010 pin map.
# Sources (local Alinx docs):
#   ~/Alinx/.../course_s1_fpga.zip (streamed 21 constraint files; 44 signals)

Board:
  id: alinx_ax7z010
  pinBanks:
    sys_clk:
      pins: U18
    cpu_resetn:
      pins: M15
    onboard_leds:
      pins: [J14, K14, J18, H18]
    ethernet_mdio:
      pins:
        mdc: J17
    ethernet_rgmii:
      pins:
        rxc: K19
        rx_ctl: K20
        rd[0]: J18
        rd[1]: K18
        rd[2]: J15
        rd[3]: K15
        txc: R21
        tx_ctl: R20
        td[0]: N17
        td[1]: N18
        td[2]: N19
        td[3]: N20
