# alinx_ax7z020 pin map.
# Source type: github_xdc
#   https://github.com/alinxalinx/AX7Z020B_2023.1/blob/master/course_s1_fpga/01_led/auto_create_project/src/constraints/led.xdc
#   https://github.com/alinxalinx/AX7Z020B_2023.1/blob/master/course_s1_fpga/11_linux_base/Vivado/auto_create_project/src/constraints/key.xdc
#   https://github.com/alinxalinx/AX7Z020B_2023.1/blob/master/course_s1_fpga/11_linux_base/Vivado/auto_create_project/src/constraints/hdmi_out.xdc

Board:
  id: alinx_ax7z020
  pinBanks:
    sys_clk:
      pins: U18
      frequency_mhz: 50
    cpu_resetn:
      pins: M15
    onboard_leds:
      pins:
      - J14
      - K14
      - J18
      - H18
    onboard_buttons:
      pins:
      - M15
      - M14
      - L17
      - L16
    hdmi_clk:
      pins:
        p: U13
    hdmi_data_p:
      pins:
      - W14
      - Y18
      - Y16
    hdmi_i2c:
      pins:
        scl: V18
        sda: V17
