# arty_z7_20 pin map.
#
# Source: Digilent Arty-Z7-20-Master.xdc (github.com/Digilent/digilent-xdc, MIT-licensed)
# Imported via tools/verify_pinmap_against_vendor.py.

Board:
  id: arty_z7_20
  fpga:
    producer: Xilinx
    family: Zynq 7000
    part: XC7Z020-1CLG400C
  defaults:
    iostandard: LVCMOS33

  pinBanks:
    onboard_buttons:
      pins: ["D19", "D20", "L20", "L19"]
    onboard_leds:
      pins: ["R14", "P14", "N16", "M14"]
    onboard_pwm_amp:
      pins:
        pwm: "R18"
        sd: "T17"
    onboard_switches:
      pins: ["M20", "M19"]
