# digilent_pynq_z1 pin map.
# Source: LiteX-Boards platform file
#   https://raw.githubusercontent.com/litex-hub/litex-boards/master/litex_boards/platforms/digilent_pynq_z1.py

Board:
  id: digilent_pynq_z1
  pinBanks:
    onboard_buttons:
      pins: [D19, D20, L20, L19]
    onboard_switches:
      pins: [M20, M19]
    onboard_leds:
      pins: [R14, P14, N16, M14, L15, G17, N15, G14, L14, M15]
