# Altera (Intel) / Agilex 9
# Top-end Direct-RF Agilex.

Producer: Altera (Intel)
Family: Agilex 9
Description: Top-end Direct-RF Agilex.
Boards:
  - Id: intel_agilex9_directrf
    BoardName: Agilex 9 Direct RF-Series Development Kit
    Devices:
      - ddr4_sodimm_socket
      - micron_n25q256a
      - microchip_ksz9031rnx
      - usb_blaster_ii_built_in
      - silabs_cp2102
      - led_discrete_generic
      - pushbutton_smd_generic
      - dip_switch_generic
    BoardProducer: intel_altera
    Chip: AGRF039R47A1E2V
    Bridges:
      - jtag
    Programmer: quartus_pgm
    BoardURL: https://www.intel.com/content/www/us/en/products/details/fpga/development-kits/agilex/9-direct-rf.html
