# Microchip (Actel) / PolarFire SoC — chip registry
# PolarFire + RISC-V quad-core. Libero SoC + SoftConsole.

Producer: Microchip (Actel)
Family: PolarFire SoC
Description: PolarFire + RISC-V quad-core. Libero SoC + SoftConsole.
DefaultToolchains:
  - libero_soc[*]
Chips:
  - Id: MPFS025T-1FCVG484E
  - Id: MPFS025T-FCSG325E
  - Id: MPFS095T-1FCSG325E
  - Id: MPFS250T-FCG1152EES
  - Id: MPFS250T-FCVG484E
  - Id: MPFS250T-FCVG484EES
