# xilinx_zcu106 pin map.
# Source: LiteX-Boards platform file
#   https://raw.githubusercontent.com/litex-hub/litex-boards/master/litex_boards/platforms/xilinx_zcu106.py

Board:
  id: xilinx_zcu106
  pinBanks:
    onboard_leds:
      pins: [AL11, AL13, AK13, AE15, AM8, AM9, AM10, AM11]
    onboard_uart:
      pins:
        cts: AP17
        rts: AM15
        tx: AL17
        rx: AH17
    pcie_clk_n:
      pins:
        pin: AB7
    pcie_clk_p:
      pins:
        pin: AB8
    pcie_rst_n:
      pins:
        pin: L8
    pcie_rx_n:
      pins: [AE1, AF3, AG1, AJ1]
    pcie_rx_p:
      pins: [AE2, AF4, AG2, AJ2]
    pcie_tx_n:
      pins: [AD3, AE5, AG5, AH3]
    pcie_tx_p:
      pins: [AD4, AE6, AG6, AH4]
