# Achronix / Speedster 22i
# Intel 22 nm Achronix FPGA. ACE.

Producer: Achronix
Family: Speedster 22i
Description: Intel 22 nm Achronix FPGA. ACE.
Boards:
  - Id: achronix_speedster22i_hd1000
    BoardName: Speedster22i HD1000 Dev Kit
    BoardProducer: achronix
    Chip: AC22iHD1000
    Bridges:
      - jtag
    Programmer: ace_pgm
    BoardURL: https://www.achronix.com/product/speedster22ihd
