# Xilinx (AMD) / Virtex 6
# 40 nm Virtex (2009). ISE 14.7 last.

Producer: Xilinx (AMD)
Family: Virtex 6
Description: 40 nm Virtex (2009). ISE 14.7 last.
Boards:
  - Id: xilinx_ml605
    BoardName: ML605
    Devices:
      - silabs_cp2103
      - microsd_socket_generic
      - led_discrete_generic
      - pushbutton_smd_generic
      - dip_switch_generic
      - ddr3_sodimm_socket
      - intel_strataflash_p30
      - micron_n25q128a
      - marvell_88e1111
      - lcd_char_16x2
      - silabs_si570
    BoardProducer: xilinx_amd
    Chip: XC6VLX240T-1FFG1156C
    Bridges:
      - jtag
    Programmer: ise_impact
    BoardURL: https://www.xilinx.com/products/boards-and-kits/ek-v6-ml605-g.html
