# Xilinx (AMD) / Virtex 4

Producer: Xilinx (AMD)
Family: Virtex 4
Description: (generated)
Boards:
  - Id: xilinx_ml401
    BoardName: Xilinx ML401 LX Evaluation Platform
    Devices:
      - led_discrete_generic
      - pushbutton_smd_generic
      - dip_switch_generic
      - lcd_char_16x2
    BoardProducer: xilinx_amd
    Chip: XC4VLX25-FF668-10
    Bridges:
      - jtag
    Programmer: ise_impact
    Features:
      - sdr_sdram
      - user_leds
      - user_buttons
      - dip_switches
      - seven_segment_display
      - usb_uart_bridge
      - jtag_header
      - ethernet_phy_gigabit
    BoardURL: https://docs.amd.com/v/u/en-US/ug080
    Status: eol
  - Id: xilinx_ml402
    BoardName: Xilinx ML402 SX Evaluation Platform
    Devices:
      - led_discrete_generic
      - pushbutton_smd_generic
      - dip_switch_generic
      - marvell_88e1111
      - lcd_char_16x2
    BoardProducer: xilinx_amd
    Chip: XC4VSX35-FF668-10
    Bridges:
      - jtag
    Programmer: ise_impact
    Features:
      - sdr_sdram
      - user_leds
      - user_buttons
      - dip_switches
      - seven_segment_display
      - usb_uart_bridge
      - jtag_header
      - ethernet_phy_gigabit
    BoardURL: https://docs.amd.com/v/u/en-US/ug080
    Status: eol
  - Id: xilinx_ml403
    BoardName: Xilinx ML403 FX Embedded PowerPC Platform
    Devices:
      - led_discrete_generic
      - pushbutton_smd_generic
      - dip_switch_generic
      - marvell_88e1111
      - lcd_char_16x2
    BoardProducer: xilinx_amd
    Chip: XC4VFX12-FF668-10
    Bridges:
      - jtag
    Programmer: ise_impact
    Features:
      - sdr_sdram
      - user_leds
      - user_buttons
      - dip_switches
      - seven_segment_display
      - usb_uart_bridge
      - jtag_header
      - ethernet_phy_gigabit
    BoardURL: https://docs.amd.com/v/u/en-US/ug080
    Status: eol
