# Xilinx (AMD) / Virtex 5

Producer: Xilinx (AMD)
Family: Virtex 5
Description: (generated)
Boards:
  - Id: xilinx_ml505
    BoardName: Xilinx ML505 LXT Evaluation Platform
    Devices:
      - led_discrete_generic
      - pushbutton_smd_generic
      - dip_switch_generic
      - marvell_88e1111
      - silabs_cp2102
      - intel_strataflash_p30
      - lcd_char_16x2
    BoardProducer: xilinx_amd
    Chip: XC5VLX50T-1FFG1136
    Bridges:
      - jtag
    Programmer: ise_impact
    Features:
      - ddr2_memory
      - dip_switches
      - ethernet_phy_gigabit
      - jtag_header
      - nor_flash
      - parallel_lcd
      - pcie_endpoint
      - sata_host
      - usb_uart_bridge
      - user_buttons
      - user_leds
    BoardURL: https://docs.amd.com/v/u/en-US/ug347
    Status: eol
  - Id: xilinx_ml506
    BoardName: Xilinx ML506 SXT Evaluation Platform
    Devices:
      - led_discrete_generic
      - pushbutton_smd_generic
      - dip_switch_generic
      - marvell_88e1111
      - silabs_cp2102
      - intel_strataflash_p30
      - lcd_char_16x2
    BoardProducer: xilinx_amd
    Chip: XC5VSX50T-1FFG1136
    Bridges:
      - jtag
    Programmer: ise_impact
    Features:
      - ddr2_memory
      - dip_switches
      - ethernet_phy_gigabit
      - jtag_header
      - nor_flash
      - parallel_lcd
      - pcie_endpoint
      - sata_host
      - usb_uart_bridge
      - user_buttons
      - user_leds
    BoardURL: https://docs.amd.com/v/u/en-US/ug347
    Status: eol
  - Id: xilinx_ml507
    BoardName: Xilinx ML507 FXT Evaluation Platform
    Devices:
      - led_discrete_generic
      - pushbutton_smd_generic
      - dip_switch_generic
      - marvell_88e1111
      - silabs_cp2102
      - lcd_char_16x2
    BoardProducer: xilinx_amd
    Chip: XC5VFX70T-1FFG1136
    Bridges:
      - jtag
    Programmer: ise_impact
    Features:
      - ddr2_memory
      - dip_switches
      - ethernet_phy_gigabit
      - jtag_header
      - parallel_lcd
      - pcie_endpoint
      - sata_host
      - usb_uart_bridge
      - user_buttons
      - user_leds
    BoardURL: https://docs.amd.com/v/u/en-US/ug347
    Status: eol
