# Gowin / Arora/GW2AR
# GW2A with embedded SDRAM.

Producer: Gowin
Family: Arora/GW2AR
Description: GW2A with embedded SDRAM.
Boards:
  - Id: gowin_gw2ar18_devkit
    BoardName: GW2AR-18 Dev Kit
    BoardProducer: gowin_semi
    Chip: GW2AR-LV18QN88C8/I7
    Bridges:
      - jtag
    Programmer: openFPGALoader
    BoardURL: https://www.gowinsemi.com/en/support/devkits_detail/33/
  - Id: tang_nano_20k
    BoardName: Tang Nano 20k
    Devices:
      - maxim_max98357
      - ws2812_led_chain
      - microsd_socket_generic
    BoardProducer: sipeed
    Chip: GW2AR-LV18QN88C8/I7
    Bridges:
      - jtag
    Programmer: openFPGALoader
    BoardURL: https://wiki.sipeed.com/hardware/en/tang/tang-nano-20k/nano-20k.html
