# gowin / aurora

Producer: gowin
Family: aurora
Description: ""
Boards:
  - Id: gowin_gw3a20_devkit
    BoardName: "GW3A-20 Starter Kit (DK_START_GW3A-LV20LQ144)"
    Devices:
      - ftdi_ft2232h
      - led_discrete_generic
      - pushbutton_smd_generic
    BoardProducer: gowin_semi
    Chip: GW3A-LV20LQ144C6/I5
    Bridges:
      - jtag
    Programmer: gowin_pgm
    Features:
      - gpio_header_generic
      - jtag_header
      - usb_jtag_bridge
      - user_buttons
      - user_leds
    BoardURL: "https://www.gowinsemi.com/en/support/devkits/37/"
    Status: active
