# Gowin / LittleBee/GW1NS

Producer: Gowin
Family: LittleBee/GW1NS
Description: (generated)
Boards:
  - Id: gowin_gw1ns4_devkit
    BoardName: GW1NS-4 SoC Starter Kit
    BoardProducer: gowin_semi
    Chip: GW1NS-LV4CQN48C7/I6
    Bridges:
      - usb-jtag
    Programmer: gowin_pgm
    ExtraProgrammers:
      - openFPGALoader[*]
    Features:
      - user_leds
      - user_buttons
      - usb_jtag_bridge
      - jtag_header
    BoardURL: https://www.gowinsemi.com/en/support/devkits_detail/32/
    Status: active
