# Microchip (Actel) / RTG4
# Rad-tolerant flash FPGA (space). Libero SoC.

Producer: Microchip (Actel)
Family: RTG4
Description: Rad-tolerant flash FPGA (space). Libero SoC.
Boards:
  - Id: microchip_rtg4_devkit
    BoardName: RTG4 Development Kit
    BoardProducer: microchip
    Chip: RT4G150-CG1657
    Bridges:
      - jtag
    Programmer: libero_fpexpress
    BoardURL: https://www.microchip.com/en-us/development-tool/RTG4-DEV-KIT
