# Pangomicro / Titan
# High-end Titan with SerDes/PCIe. PDS.

Producer: Pangomicro
Family: Titan
Description: High-end Titan with SerDes/PCIe. PDS.
Boards:
  - Id: pangomicro_pgt180h_devkit
    BoardName: PGT180H Development Kit
    BoardProducer: pangomicro
    Chip: PGT180HFBG484
    Bridges:
      - jtag
    Programmer: pango_pgm
    BoardURL: https://www.pangomicro.com/en/Page/index/cid/4.html
