# alchitry_pt pin map.
# Source: LiteX-Boards platform file
#   https://raw.githubusercontent.com/litex-hub/litex-boards/master/litex_boards/platforms/alchitry_pt_v2.py

Board:
  id: alchitry_pt
  pinBanks:
    sys_clk:
      pins: W19
    cpu_resetn:
      pins: N15
    onboard_leds:
      pins: [P19, P20, T21, R19, V22, U21, T20, W20]
    onboard_uart:
      pins:
        tx: AA21
        rx: AA20
    qspi_flash_cs_n:
      pins:
        pin: T19
    qspi_flash_dq:
      pins: [P22, R22, P21, R21]
    qspi_flash_hold:
      pins:
        pin: R21
    qspi_flash_miso:
      pins:
        pin: R22
    qspi_flash_mosi:
      pins:
        pin: P22
    qspi_flash_wp:
      pins:
        pin: P21
