# Mapping of physical boards to their variant directories

Boards:
  - id: a7_lite_35t
    representative: a7_lite_35t
    variants:
      - a7_lite_35t
  - id: alinx_ax301
    representative: alinx_ax301
    variants:
      - alinx_ax301
  - id: alinx_ax4010
    representative: alinx_ax4010
    variants:
      - alinx_ax4010
  - id: alinx_ax7035b
    representative: alinx_ax7035b
    variants:
      - alinx_ax7035b
  - id: arty_a7
    representative: arty_a7_100
    variants:
      - arty_a7_35
      - arty_a7_35_pmod_mic3
      - arty_a7_100
      - arty_a7_100_pmod_mic3
  - id: basys3
    representative: basys3
    variants:
      - basys3
  - id: c5gx
    representative: c5gx
    variants:
      - c5gx
  - id: colorlight75b
    representative: colorlight75b_tm1638_ecp5_yosys
    variants:
      - colorlight75b_tm1638_ecp5_yosys
  - id: de0
    representative: de0
    variants:
      - de0
  - id: de0_cv
    representative: de0_cv
    variants:
      - de0_cv
  - id: de0_nano
    representative: de0_nano_vga_pmod
    variants:
      - de0_nano_vga666
      - de0_nano_vga_pmod
  - id: de0_nano_soc
    representative: de0_nano_soc_vga_pmod
    variants:
      - de0_nano_soc_vga666
      - de0_nano_soc_vga_pmod
  - id: de1
    representative: de1
    variants:
      - de1
  - id: de1_soc
    representative: de1_soc
    variants:
      - de1_soc
  - id: de2
    representative: de2
    variants:
      - de2
  - id: de2_115
    representative: de2_115
    variants:
      - de2_115
  - id: de10_lite
    representative: de10_lite
    variants:
      - de10_lite
      - de10_lite_tm1638_virtual_switches
  - id: de10_nano
    representative: de10_nano
    variants:
      - de10_nano
  - id: dk_dev_3c120n
    representative: dk_dev_3c120n
    variants:
      - dk_dev_3c120n
  - id: eclypse_z7
    representative: eclypse_z7
    variants:
      - eclypse_z7
  - id: emooc_cc
    representative: emooc_cc
    variants:
      - emooc_cc
  - id: ice40hx8k_evb
    representative: ice40hx8k_evb_yosys
    variants:
      - ice40hx8k_evb_yosys
  - id: icebreaker
    representative: icebreaker_bare
    variants:
      - icebreaker_bare
      - icebreaker_dvi_12b_no_tm1638_yosys
      - icebreaker_dvi_12b_tm1638_yosys
      - icebreaker_dvi_24b_no_tm1638_yosys
      - icebreaker_dvi_24b_tm1638_yosys
      - icebreaker_no_dvi_no_tm1638_yosys
      - icebreaker_no_dvi_tm1638_yosys
  - id: karnix_ecp5
    representative: karnix_ecp5_yosys
    variants:
      - karnix_ecp5_yosys
  - id: marsohod3gw2
    representative: marsohod3gw2
    variants:
      - marsohod3gw2
  - id: marsohod_mcy316
    representative: marsohod_mcy316
    variants:
      - marsohod_mcy316
  - id: nexys4
    representative: nexys4
    variants:
      - nexys4
  - id: nexys4_ddr
    representative: nexys4_ddr
    variants:
      - nexys4_ddr
  - id: nexys_a7
    representative: nexys_a7
    variants:
      - nexys_a7
      - nexys_a7_50
      - nexys_a7_100
  - id: omdazz
    representative: omdazz
    variants:
      - omdazz
      - omdazz_pmod_mic3
  - id: omdazz_epm570
    representative: omdazz_epm570
    variants:
      - omdazz_epm570
      - omdazz_epm570_quartus_13_1_or_older
  - id: orangecrab_ecp5
    representative: orangecrab_ecp5_yosys
    variants:
      - orangecrab_ecp5_yosys
  - id: orangepi_msoc
    representative: orangepi_msoc
    variants:
      - orangepi_msoc
  - id: piswords6
    representative: piswords6
    variants:
      - piswords6
  - id: qmtech_kintex_7
    representative: qmtech_kintex_7
    variants:
      - qmtech_kintex_7
  - id: rzrd
    representative: rzrd
    variants:
      - rzrd
      - rzrd_pmod_mic3
  - id: saylinx
    representative: saylinx
    variants:
      - saylinx
      - saylinx_pmod_mic3
  - id: tang_mega_138k
    representative: tang_mega_138k_lcd_480_272_tm1638
    variants:
      - tang_mega_138k_lcd_480_272_tm1638
  - id: tang_mega_138k_pro
    representative: tang_mega_138k_pro_lcd_480_272_no_tm1638
    variants:
      - tang_mega_138k_pro_lcd_480_272_no_tm1638
      - tang_mega_138k_pro_lcd_480_272_tm1638
  - id: tang_nano_4k
    representative: tang_nano_4k_hdmi_no_tm1638
    variants:
      - tang_nano_4k_hdmi_no_tm1638
      - tang_nano_4k_hdmi_tm1638
  - id: tang_nano_9k
    representative: tang_nano_9k_lcd_480_272_no_tm1638
    variants:
      - tang_nano_9k_hdmi_no_ip_tm1638
      - tang_nano_9k_hdmi_no_tm1638
      - tang_nano_9k_hdmi_tm1638
      - tang_nano_9k_lcd_480_272_no_tm1638
      - tang_nano_9k_lcd_480_272_no_tm1638_yosys
      - tang_nano_9k_lcd_480_272_tm1638
      - tang_nano_9k_lcd_480_272_tm1638_hackathon
      - tang_nano_9k_lcd_480_272_tm1638_yosys
      - tang_nano_9k_lcd_800_480_no_tm1638
      - tang_nano_9k_lcd_800_480_no_tm1638_yosys
      - tang_nano_9k_lcd_800_480_tm1638
      - tang_nano_9k_lcd_800_480_tm1638_hackathon
      - tang_nano_9k_lcd_800_480_tm1638_yosys
      - tang_nano_9k_lcd_ml6485_no_tm1638_yosys
      - tang_nano_9k_lcd_ml6485_tm1638_yosys
      - tang_nano_9k_tm1638_sd
  - id: tang_nano_20k
    representative: tang_nano_20k_lcd_480_272_no_tm1638
    variants:
      - tang_nano_20k_hdmi_no_tm1638
      - tang_nano_20k_hdmi_tm1638
      - tang_nano_20k_lcd_480_272_no_tm1638
      - tang_nano_20k_lcd_480_272_tm1638
      - tang_nano_20k_lcd_800_480_no_tm1638
      - tang_nano_20k_lcd_800_480_tm1638
      - tang_nano_20k_lcd_800_480_tm1638_alt
  - id: tang_primer_20k_dock
    representative: tang_primer_20k_dock_no_hdmi_no_tm1638
    variants:
      - tang_primer_20k_dock_hdmi_no_tm1638
      - tang_primer_20k_dock_hdmi_no_tm1638_yosys
      - tang_primer_20k_dock_hdmi_tm1638
      - tang_primer_20k_dock_hdmi_tm1638_alt
      - tang_primer_20k_dock_hdmi_tm1638_yosys
      - tang_primer_20k_dock_lcd_800_480_no_tm1638
      - tang_primer_20k_dock_lcd_800_480_tm1638
      - tang_primer_20k_dock_lcd_800_480_tm1638_alt
      - tang_primer_20k_dock_no_hdmi_no_tm1638
      - tang_primer_20k_dock_no_hdmi_tm1638
  - id: tang_primer_20k_lite
    representative: tang_primer_20k_lite
    variants:
      - tang_primer_20k_lite
  - id: tang_primer_25k
    representative: tang_primer_25k_pmod_vga
    variants:
      - tang_primer_25k_pmod_hdmi
      - tang_primer_25k_pmod_hub75e_led_matrix
      - tang_primer_25k_pmod_hub75e_led_matrix_bright
      - tang_primer_25k_pmod_vga
  - id: terasic_sockit
    representative: terasic_sockit
    variants:
      - terasic_sockit
  - id: zeowaa
    representative: zeowaa
    variants:
      - zeowaa
      - zeowaa_wo_dig_0
  - id: zybo_z7
    representative: zybo_z7
    variants:
      - zybo_z7
