# terasic_de10_pro_stratix10_gx pin map.
# Source: Terasic user manual PDF
#   ~/Terasic/DE10-Pro_SX_User_Manual_RevE.pdf

Board:
  id: terasic_de10_pro_stratix10_gx
  pinBanks:
    onboard_buttons:
      pins: [PIN_D24, PIN_D23]
    onboard_switches:
      pins: [PIN_C23, PIN_B23]
    onboard_leds:
      pins: [PIN_B24, PIN_A24, PIN_A25, PIN_A26]
