# Efinix / Trion — chip registry
# 40 nm Quantum-architecture FPGA. Efinity.

Producer: Efinix
Family: Trion
Description: 40 nm Quantum-architecture FPGA. Efinity.
DefaultToolchains:
  - efinity[*]
Chips:
  - Id: T120F324C
  - Id: T120F324C4
  - Id: T120F576C4
  - Id: T13F169C3
  - Id: T20F169C3
  - Id: T20F256C2
  - Id: T35F324C3
  - Id: T8F81
  - Id: T8F81C2
  - Id: T8Q144C3
