# alinx_ax7325 pin map.
# Source (local Alinx docs):
#   ~/Alinx/AX7325B/CD/01_学习教程之例程篇/demo/01_1_led_test/led_test/led_test.srcs/constrs_1/new/led.xdc

Board:
  id: alinx_ax7325
  pinBanks:
    sys_clk_p:
      pins: AE10
      frequency_mhz: 200
    cpu_resetn:
      pins: AG27
    onboard_leds:
      pins: [A22, C19, B19, E18]
