# Anlogic / Elf EF2
# Anlogic Elf 2. TD.

Producer: Anlogic
Family: Elf EF2
Description: Anlogic Elf 2. TD.
Boards:
  - Id: anlogic_ef2_devkit
    BoardName: Elf EF2 Dev Kit
    BoardProducer: anlogic
    Chip: EF2L45LG144C
    Bridges:
      - jtag
    Programmer: td_pgm

    Status: eol