# Anlogic / Phoenix EF3
# Anlogic Phoenix. TD.

Producer: Anlogic
Family: Phoenix EF3
Description: Anlogic Phoenix. TD.
Boards:
  - Id: anlogic_ef3_devkit
    BoardName: Phoenix EF3 Dev Kit
    BoardProducer: anlogic
    Chip: EF3L185BG256C
    Bridges:
      - jtag
    Programmer: td_pgm
    BoardURL: https://www.anlogic.com/eng/prod/56.html
