# Anlogic / Salomon SL2
# Anlogic Salomon high-end (2023+).

Producer: Anlogic
Family: Salomon SL2
Description: Anlogic Salomon high-end (2023+).
Boards:
  - Id: anlogic_sl2_devkit
    BoardName: Salomon SL2 Dev Kit
    BoardProducer: anlogic
    Chip: SL2A28
    Bridges:
      - jtag
    Programmer: td_pgm

    Status: eol