# Anlogic / Salt SL
# Anlogic Salt low-cost. TD.

Producer: Anlogic
Family: Salt SL
Description: Anlogic Salt low-cost. TD.
Boards:
  - Id: anlogic_sl_devkit
    BoardName: Salt SL Dev Kit
    BoardProducer: anlogic
    Chip: SL18C
    Bridges:
      - jtag
    Programmer: td_pgm
    BoardURL: https://www.anlogic.com/eng/prod/57.html
