# Gowin / AroraV/GW5AST — chip registry
# GW5A with safety/security features.

Producer: Gowin
Family: AroraV/GW5AST
Description: GW5A with safety/security features.
DefaultToolchains:
  - gowin_standard[*]
Chips:
  - Id: GW5AST-LV138FPG676AES
  - Id: GW5AST-LV138PG484AC1/I0
