# Gowin / AroraV/GW5A — chip registry
# 22 nm high-end Gowin (Arora V). gowin_standard.

Producer: Gowin
Family: AroraV/GW5A
Description: 22 nm high-end Gowin (Arora V). gowin_standard.
DefaultToolchains:
  - gowin_standard[*]
  - nextpnr_apicula[*]
Chips:
  - Id: GW5A-LV25MG121NC1/I0
  - Id: GW5A-LV25MG121NES
  - Id: GW5A-LV25UG324C1/I0
  - Id: GW5AR-LV15MG132PC1/I0
