# NanoXplore / NG-LARGE
# Rad-hard European FPGA, larger. NanoXmap.

Producer: NanoXplore
Family: NG-LARGE
Description: Rad-hard European FPGA, larger. NanoXmap.
Boards:
  - Id: nanoxplore_ng_large_evk
    BoardName: NG-LARGE Evaluation Kit
    BoardProducer: nanoxplore
    Chip: NG-LARGE-CG484
    Bridges:
      - jtag
    Programmer: nanoxmap_impulse
    BoardURL: "https://www.nanoxplore.com"
