# NanoXplore / NG-MEDIUM
# Rad-hard European FPGA, mid-range. NanoXmap.

Producer: NanoXplore
Family: NG-MEDIUM
Description: Rad-hard European FPGA, mid-range. NanoXmap.
Boards:
  - Id: nanoxplore_ng_medium_evk
    BoardName: NG-MEDIUM Development Kit
    BoardProducer: nanoxplore
    Chip: NG-MEDIUM-CG289
    Bridges:
      - jtag
    Programmer: nanoxmap_impulse
    BoardURL: "https://www.nanoxplore.com"
