# NanoXplore / NG-ULTRA
# Rad-hard space-grade FPGA (ESA / CNES). NanoXmap.

Producer: NanoXplore
Family: NG-ULTRA
Description: Rad-hard space-grade FPGA (ESA / CNES). NanoXmap.
Boards:
  - Id: nanoxplore_ng_ultra_evk
    BoardName: NG-ULTRA Evaluation Kit
    BoardProducer: nanoxplore
    Chip: NG-ULTRA-CG1156
    Bridges:
      - jtag
    Programmer: nanoxmap_impulse
    BoardURL: "https://www.nanoxplore.com"
