# Xilinx (AMD) / Virtex 5 — chip registry
# 65 nm Virtex (2006). ISE 14.7 last supporting release.

Producer: Xilinx (AMD)
Family: Virtex 5
Description: 65 nm Virtex (2006). ISE.
DefaultToolchains:
  - ise[*]
Chips:
  - Id: XC5VFX70T-1FFG1136
  - Id: XC5VLX50T-1FFG1136
  - Id: XC5VSX50T-1FFG1136
