# Xilinx (AMD) / Zynq Ultrascale+ — chip registry
# 16 nm A53 quad + R5 + UltraScale+ PL MPSoC. Vivado.

Producer: Xilinx (AMD)
Family: Zynq Ultrascale+
Description: 16 nm A53 quad + R5 + UltraScale+ PL MPSoC. Vivado.
DefaultToolchains:
  - vivado[*]
Chips:
  - Id: XCK24-SFVC784
  - Id: XCK26-SFVC784
  - Id: XCU25
  - Id: XCZU11EG-2FFVC1156E
  - Id: XCZU11EG-2FFVC1156I
  - Id: XCZU11EG-2FFVF1517I
  - Id: XCZU15EG-1FFVC900I
  - Id: XCZU15EG-2FFVB1156I
  - Id: XCZU17EG-2FFVC1760I
  - Id: XCZU17EG-2FFVD1760E
  - Id: XCZU19EG-2FFVB1517I
  - Id: XCZU19EG-2FFVC1760I
  - Id: XCZU19EG-2FFVD1760E
  - Id: XCZU19EG-2FFVD1760I
  - Id: XCZU1CG-1SBVA484
  - Id: XCZU2CG-1SFVC784E
  - Id: XCZU2EG-1SFVC784I
  - Id: XCZU2EG-L1SFVC784I4524
  - Id: XCZU3CG-L1SFVC784I
  - Id: XCZU3EG
  - Id: XCZU3EG-1SBVA484E
  - Id: XCZU3EG-1SFVA625
  - Id: XCZU3EG-1SFVA625I
  - Id: XCZU3EG-1SFVC784E
  - Id: XCZU3EG-1SFVC784I
  - Id: XCZU3EG-2SBVA484I
  - Id: XCZU3EG-2SFVC784E
  - Id: XCZU3EG-SFVC784
  - Id: XCZU4EV-1SFVC784E
  - Id: XCZU4EV-1SFVC784I
  - Id: XCZU4EV-2SFVC784I
  - Id: XCZU5EG-1SFVC784
  - Id: XCZU5EV-1SFVC784I
  - Id: XCZU5EV-2SFVC784I
  - Id: XCZU7CG-2FFVC1156E
  - Id: XCZU7EV
  - Id: XCZU7EV-1FBVB900I
  - Id: XCZU7EV-1FFVC1156E
  - Id: XCZU7EV-1FFVC1156I
  - Id: XCZU7EV-1FFVF1517E
  - Id: XCZU7EV-2FBVB900I
  - Id: XCZU7EV-2FFVC1156E
  - Id: XCZU7EV-FBVB900
  - Id: XCZU9EG-1FFVC900I
  - Id: XCZU9EG-2FFVB1156E
  - Id: XCZU9EG-2FFVB1156I
  - Id: XCZU9EG-2FFVC900I
  - Id: xczu1cgsbva484-1
  - Id: xczu3eg-1sfvc784e
  - Id: xczu5ev-2sfvc784i
  - Id: XCZU7EV-2FFVC1156I
  - Id: XCK26-SFVC784-2LV-C
  - Id: XCZU15EG-2FFVC900I
