# Lattice / CertusPro-NX
# Larger Nexus FPGA. Radiant + nextpnr-nexus.

Producer: Lattice
Family: CertusPro-NX
Description: Larger Nexus FPGA. Radiant + nextpnr-nexus.
Boards:
  - Id: lattice_certuspro_nx_evn
    BoardName: CertusPro-NX Evaluation Board
    Devices:
      - ftdi_ft2232h
      - microsd_socket_generic
    BoardProducer: lattice
    Chip: LFCPNX-100-9LFG672C
    Bridges:
      - jtag
    Programmer: openFPGALoader
    BoardURL: https://www.latticesemi.com/products/developmentboardsandkits/certuspro-nx-evaluation-board
  - Id: lattice_certuspro_nx_pcieb
    BoardName: CertusPro-NX PCIe Bridge Board
    Devices:
      - ftdi_ft2232h
    BoardProducer: lattice
    Chip: LFCPNX-100-9LFG672I
    Bridges:
      - jtag
    Programmer: radiant_pgm
    Features:
      - qspi_flash
      - fmc_lpc
      - usb_uart_bridge
      - user_leds
      - user_buttons
      - usb_jtag_bridge
      - usb_powered
    BoardURL: https://www.latticesemi.com/products/developmentboardsandkits/certuspro-nx-pcie-bridge-board
    Status: active
  - Id: lattice_certuspro_nx_vvml
    BoardName: CertusPro-NX Voice & Vision Machine Learning Board
    Devices:
      - ftdi_ft2232h
    BoardProducer: lattice
    Chip: LFCPNX-100-9LFG672I
    Bridges:
      - jtag
    Programmer: radiant_pgm
    Features:
      - hyperram
      - qspi_flash
      - mipi_csi2_input
      - usb_2_otg
      - usb_uart_bridge
      - pmod_connector
      - user_leds
      - user_buttons
      - usb_powered
      - usb_jtag_bridge
    BoardURL: https://www.latticesemi.com/certuspro-nx-vvml-board
    Status: active
