# Lattice / CrossLink-NX

Producer: Lattice
Family: CrossLink-NX
Description: (generated)
Boards:
  - Id: lattice_crosslinku_nx_evn
    BoardName: CrossLinkU-NX Evaluation Board
    BoardProducer: lattice
    Chip: LIFCLU-33-9BG400I
    Bridges:
      - jtag
    Programmer: radiant_pgm
    ExtraProgrammers:
      - openFPGALoader[*]
    Features:
      - hyperram
      - qspi_flash
      - mipi_csi2_input
      - usb_2_otg
      - usb_uart_bridge
      - pmod_connector
      - raspi_hat_header
      - user_leds
      - user_buttons
      - dip_switches
      - usb_jtag_bridge
      - usb_powered
    BoardURL: https://www.latticesemi.com/en/Products/DevelopmentBoardsAndKits/CrossLinkU-NX-Evaluation-Board
    Status: active
